#!/bin/bash
subject=MSC06
work_dir=/tmp
data_dir=/home/faird/shared/projects/MSC_to_DCAN/split_halves/half1
run_folder=/home/faird/shared/projects/wlf-test/LuciDev/ILI-reliability-wrapper
out_dir=/home/faird/shared/projects/wlf-test/LuciDev/ILI-reliability-wrapper/CORR_OUT/5min
half2_ILI=/home/faird/shared/projects/wlf-test/LuciDev/ILI-reliability-wrapper/half2_ILI
min=5min

# running on seven target roi
rois_dir=/home/faird/shared/projects/wlf-test/fr/output-half-HCP
two_customized_roi_dir=/home/faird/shared/projects/wlf-test/fr/IFGVAN-roi-customized
config_file=${run_folder}/config.json
correlation_script=${run_folder}/intrasubject_similarity.py

singularity=`which singularity`
MRE="/home/faird/shared/code/external/utilities/MATLAB_Runtime_R2019a_update9/v96"

LR_outdir=${work_dir}/${subject}/LR
if [ ! -d "${LR_outdir}" ]; then
    mkdir -p "${LR_outdir}"
fi

## RUN crossotope.sif on x min sample of half1 dtseries for 7 ROIS to generate L&R values
for roi_dir in "$rois_dir"/L_{55b,V1,4,FEF,FFC}_ROI/ ${two_customized_roi_dir}/{new_IFG_roi,VAN_MTG}; do
    echo "$roi_dir"
    roi=$(basename "$roi_dir")

    subdir="${data_dir}/${subject}"
    dtseries=${subject}_half1.dtseries.nii
    motion=${subject}_half1_power_2014_FD_only.mat

    env -i ${singularity} run \
    -B ${subdir}:/session \
    -B ${roi_dir}:/input_rois \
    -B ${MRE}:/matlab \
    -B ${config_file}:/config.json \
    -B ${LR_outdir}:/output \
    /home/faird/shared/projects/wlf-test/fr/crossotope_mapping/crossotope.sif analysis \
    --roi_dir /input_rois --n_samples 100 --matlab "$(which matlab)" --MRE /matlab \
    --json_config /config.json --label ${roi} \
    /session/{${dtseries},${motion}}
done

## RUN ILI on x min sample of half1 dtseries for 7 ROIS
#first remove hashes from csv files in output dir of prior step (should contain 7 total)
for csv_file in `ls ${LR_outdir}/*.csv`; do
    sed 's|# ||' <${csv_file} >${LR_outdir}/blah.csv
    mv ${LR_outdir}/blah.csv ${csv_file}
    sed -i '/^$/d' ${csv_file}
    sed -i '/^,/d' ${csv_file}
    awk -F',' 'NF==4 {print}' ${csv_file} >> ${LR_outdir}/blah.csv
    mv ${LR_outdir}/blah.csv ${csv_file}
done

# Run the crossotope.sif ili, where input is LR_outdir containing 7 csv files generated in prior step (eg out/5min/MSC01/LR) and output is a new output folder called ILI to store ILI csv (eg out/5min/MSC01/ILI)

#Make ILI output directory if it doesn't already exist
ILI_outdir=${work_dir}/${subject}/ILI
if [ ! -d "${ILI_outdir}" ]; then
    mkdir -p "${ILI_outdir}"
fi

singularity run \
    -B "${LR_outdir}:/input" \
    -B "${ILI_outdir}:/output" \
    /home/faird/shared/projects/wlf-test/fr/crossotope_mapping/crossotope.sif ili /input /output/output.csv

## Run correlation
half1_csv=${ILI_outdir}/output.csv
half2_csv=${half2_ILI}/${subject}/output.csv

correlation=$(python3 ${correlation_script} ${half1_csv} ${half2_csv})
echo "$correlation" >> ${out_dir}/${subject}_${min}_correlation.csv
